server:
  shutdown: graceful

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Dev/h2/bin/demo
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2

management:
  endpoints:
    web:
      exposure:
        include: "health"

logging:
  level:
    ROOT: INFO
#    org.hibernate: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
#    org.springframework.orm: DEBUG
#    org.springframework.transaction: DEBUG
#    com.zaxxer.hikari: TRACE
#    com.mysql.cj.jdbc: TRACE



application:
  kafka:
    producer:
      default:
        bootstrap-server: "kafka.hj2server.ddns.net:9092"
        linger-ms: 10
      order-request:
        bootstrap-server: "kafka.hj2server.ddns.net:9092"
        topic: "toy-assignment-order-request-event"
        linger-ms: 10